

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres


development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: career_path_development
  pool: 5
  username: postgres
  password:

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: career_path_test
  pool: 5
  username: postgres
  password:

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: career_path_production
  pool: 5
  username: postgres
  password:



